%hidden MODULE_NAME='ram'

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󰍛 "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_green}"
set -ogq "@catppuccin_${MODULE_NAME}_text" " #(~/.config/tmux/plugins/tmux-cpu/scripts/ram_percentage.sh)"

source -F '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/utils/status_module.conf'
